services:
  app:
    image: quiero-recordarte-app
    command: bash -c 'rm -f /rails/tmp/pids/server.pid && bundle exec bin/rails db:migrate && bundle exec bin/rails db:seed && bundle exec bin/rails s -p 3000 -b 0.0.0.0'
    build:
      context: .
    ports:
      - "3000:3000" # Puma (Rails app)
    volumes:
      - .:/rails
