services:
  app:
    image: quiero-recordarte-app
    command: bash -c 'bundle exec bin/rails db:reset && bundle exec bin/rails s -p 3000 -b 0.0.0.0'
    build:
      context: .
    ports:
      - "3000:3000" # Puma (Rails app)
    volumes:
      - .:/rails
